version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: nerus
      MYSQL_DATABASE: nerus
      MYSQL_USER: nerus
      MYSQL_PASSWORD: nerus
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local